google_analytics: UA-XXXXXXXX-X
show_modal_on_finish_post: false
medium_username: medium_username
paginate: 5
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
highlighter: rouge
twitter_username: twitter_username
use_logo: false
show_time_bar: false
instagram_username: instagram_username
show_modal_on_exit: false
name: TamilGun
permalink: /:title/
paginate_path: /page/:num/
sass:
  style: compressed
markdown: kramdown
url: https://tamilgun.isaiminiweb.online
facebook_username: facebook_username
sent_message_url: /contact/message-sent/
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: --page-break--
  permalink: /:num/
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true
categories_folder: category
github_username: github_username
disqus_username: disqus_username
collections:
  authors:
    output: true
linkedin_username: linkedin_username
version: live
title: TamilGun
language: en
description: Watch and Download Tamil, Telugu, Hindi, Malayalam, Kannada,
  English, Movies and Web series 2020
tags:
  - tamil
  - hindi
  - telugu
  - malayalam
  - kannada
  - webseries
  - english
exclude:
  - package.json
  - package-lock.json
  - src
  - node_modules
  - initpost.sh
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - README.md
show_get_theme_btn: false
show_hero: true
email: youremail@test.com
baseurl: ""
two_columns_layout: true
menu:
  - title: Tamil Movies  2012
    url: /category/tamil-movies-2012
